/*
 * Lum Transform Dialect Emitter Implementation
 */

#include "transform_emitter.hpp"
#include <algorithm>

namespace lum {

std::string TransformEmitter::emit(const Program& program) {
    // Clear state
    output_.str("");
    output_.clear();
    ssaCounter_ = 0;
    handles_.clear();
    errors_.clear();

    // Emit module header with transform attribute
    line("// Generated by Lum DSL Compiler");
    line("// Transform Dialect MLIR");
    line();
    line("module attributes {transform.with_named_sequence} {");
    indentLevel_++;

    // For each schedule, emit a named sequence
    for (const auto& schedule : program.getSchedules()) {
        // Find the associated pattern
        const PatternDecl* pattern = nullptr;
        if (schedule->isPatternTarget()) {
            pattern = program.findPattern(schedule->getTarget());
            if (!pattern) {
                errors_.push_back("Schedule '" + schedule->getName() +
                                "' references unknown pattern '" +
                                schedule->getTarget() + "'");
                continue;
            }
        }

        emitSchedule(*schedule, pattern);
        line();
    }

    // Close module
    indentLevel_--;
    line("}");

    return output_.str();
}

void TransformEmitter::emitSchedule(const ScheduleDecl& schedule,
                                     const PatternDecl* pattern) {
    // Reset per-schedule state
    ssaCounter_ = 0;
    handles_.clear();

    // Emit named_sequence header with readonly attribute
    indent();
    line("transform.named_sequence @" + schedule.getName() +
         "(%arg0: !transform.any_op {transform.readonly}) {");
    indentLevel_++;

    // Emit pattern matching
    if (pattern) {
        emitPattern(*pattern);
    } else {
        // Direct op type target (e.g., linalg.matmul)
        std::string handle = newSSAName("op");
        indent();
        emit(handle + " = transform.structured.match ");
        emit("ops{[\"" + schedule.getTarget() + "\"]} in %arg0");
        emit(" : (!transform.any_op) -> !transform.any_op\n");

        // Use default handle name based on op type
        std::string opName = schedule.getTarget();
        size_t dot = opName.find('.');
        if (dot != std::string::npos) {
            opName = opName.substr(dot + 1);
        }
        // Abbreviate common names
        if (opName == "matmul") opName = "mm";
        else if (opName == "generic") opName = "gen";
        else if (opName == "conv_2d") opName = "conv";
        else if (opName == "batch_matmul") opName = "bmm";

        registerHandle(opName, handle);
    }

    line();

    // Emit transforms
    for (const auto& transform : schedule.getTransforms()) {
        emitTransform(*transform);
    }

    // Emit yield
    indent();
    line("transform.yield");

    indentLevel_--;
    indent();
    line("}");
}

void TransformEmitter::emitPattern(const PatternDecl& pattern) {
    // Emit match for each op in pattern
    for (const auto& op : pattern.getOps()) {
        std::string handle = newSSAName(op->getHandle());
        indent();
        emit(handle + " = transform.structured.match ");
        emit("ops{[\"" + op->getQualifiedName() + "\"]} in %arg0");
        emit(" : (!transform.any_op) -> !transform.any_op\n");
        registerHandle(op->getHandle(), handle);
    }

    // TODO: Emit dataflow constraints verification
    // For now, we trust the pattern matches correctly
}

void TransformEmitter::emitTransform(const Transform& transform) {
    switch (transform.getKind()) {
        case NodeKind::TileTransform:
            emitTile(static_cast<const TileTransform&>(transform));
            break;
        case NodeKind::FuseTransform:
            emitFuse(static_cast<const FuseTransform&>(transform));
            break;
        case NodeKind::VecTransform:
            emitVec(static_cast<const VecTransform&>(transform));
            break;
        case NodeKind::CheckTransform:
            emitCheck(static_cast<const CheckTransform&>(transform));
            break;
        default:
            errors_.push_back("Unsupported transform type");
            break;
    }
}

void TransformEmitter::emitTile(const TileTransform& tile) {
    // Determine target handle
    std::string targetLum;
    if (tile.hasExplicitTarget()) {
        targetLum = tile.getTarget();
    } else {
        // Use first registered handle (implicit target)
        if (handles_.empty()) {
            errors_.push_back("No handle available for tile operation");
            return;
        }
        targetLum = handles_.begin()->first;
    }

    std::string targetSSA = getHandle(targetLum);
    if (targetSSA.empty()) {
        errors_.push_back("Unknown handle '" + targetLum + "' for tile");
        return;
    }

    // Generate result handles - use %loops:N syntax for loop handles
    std::string tiledHandle = newSSAName("tiled");
    size_t numLoops = tile.getSizes().size();

    // Emit tile_using_for with proper type annotation
    // Format: %tiled, %loops:3 = transform.structured.tile_using_for %op tile_sizes [4, 4, 4]
    //         : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)
    indent();
    emit(tiledHandle + ", %loops:" + std::to_string(numLoops));
    emit(" = transform.structured.tile_using_for " + targetSSA);
    emit(" tile_sizes [");
    for (size_t i = 0; i < tile.getSizes().size(); ++i) {
        if (i > 0) emit(", ");
        emit(std::to_string(tile.getSizes()[i]));
    }
    emit("]");

    // Emit type annotation: (!transform.any_op) -> (!transform.any_op, ...)
    emit(" : (!transform.any_op) -> (!transform.any_op");
    for (size_t i = 0; i < numLoops; ++i) {
        emit(", !transform.any_op");
    }
    emit(")\n");

    // Mark target consumed, rebind to tiled
    consumeHandle(targetLum, "tile");
    rebindHandle(targetLum, tiledHandle);

    // Register loop handles using %loops#N syntax for access
    if (tile.hasBindings()) {
        for (size_t i = 0; i < tile.getBindings().size() && i < numLoops; ++i) {
            if (tile.getBindings()[i] != "_") {
                std::string loopRef = "%loops#" + std::to_string(i);
                registerHandle(tile.getBindings()[i], loopRef);
            }
        }
    }
}

void TransformEmitter::emitFuse(const FuseTransform& fuse) {
    // Get producer handle
    const auto& producers = fuse.getProducers();
    if (producers.empty()) {
        errors_.push_back("Fuse requires at least one producer");
        return;
    }

    std::string producerSSA = getHandle(producers[0]);
    if (producerSSA.empty()) {
        errors_.push_back("Unknown producer handle '" + producers[0] + "'");
        return;
    }

    // Get loop handle
    std::string loopSSA = getHandle(fuse.getLoop());
    if (loopSSA.empty()) {
        errors_.push_back("Unknown loop handle '" + fuse.getLoop() + "'");
        return;
    }

    // Generate fused handles
    std::string fusedHandle = newSSAName("fused");
    std::string newLoopHandle = newSSAName("new_loop");

    // Emit fuse_into_containing_op with type annotation
    // Format: %fused, %new_loop = transform.structured.fuse_into_containing_op %producer into %loop
    //         : (!transform.any_op, !transform.any_op) -> (!transform.any_op, !transform.any_op)
    indent();
    emit(fusedHandle + ", " + newLoopHandle + " = transform.structured.fuse_into_containing_op ");
    emit(producerSSA + " into " + loopSSA);
    emit(" : (!transform.any_op, !transform.any_op) -> (!transform.any_op, !transform.any_op)\n");

    // Mark producer consumed, rebind to fused
    consumeHandle(producers[0], "fuse");
    rebindHandle(producers[0], fusedHandle);
}

void TransformEmitter::emitVec(const VecTransform& vec) {
    // Determine target handle
    std::string targetLum;
    if (vec.hasExplicitTarget()) {
        targetLum = vec.getTarget();
    } else {
        // Use first registered handle
        if (handles_.empty()) {
            errors_.push_back("No handle available for vec operation");
            return;
        }
        targetLum = handles_.begin()->first;
    }

    std::string targetSSA = getHandle(targetLum);
    if (targetSSA.empty()) {
        errors_.push_back("Unknown handle '" + targetLum + "' for vec");
        return;
    }

    // Emit vectorize with type annotation
    // Format: transform.structured.vectorize %op vector_sizes [4, 4, 4] : !transform.any_op
    indent();
    emit("transform.structured.vectorize " + targetSSA + " vector_sizes [");

    // Use the actual sizes specified (don't pad artificially)
    const auto& sizes = vec.getSizes();
    for (size_t i = 0; i < sizes.size(); ++i) {
        if (i > 0) emit(", ");
        emit(std::to_string(sizes[i]));
    }
    emit("] : !transform.any_op\n");

    // Vectorize consumes the handle
    consumeHandle(targetLum, "vectorize");
}

void TransformEmitter::emitCheck(const CheckTransform& check) {
    // Check is a verification directive, emit as comment for now
    indent();
    emit("// check " + check.getCheckType() + " (verification point)\n");

    // In a full implementation, this would:
    // 1. Clone the current IR
    // 2. Generate test inputs
    // 3. Execute both versions
    // 4. Compare results
}

// Handle management

std::string TransformEmitter::newSSAName(const std::string& hint) {
    std::string name = "%" + hint;
    if (hint.empty()) {
        name = "%v" + std::to_string(ssaCounter_);
    }
    ssaCounter_++;
    return name;
}

void TransformEmitter::registerHandle(const std::string& lumName,
                                       const std::string& ssaName) {
    handles_[lumName] = HandleInfo{ssaName, false, ""};
}

std::string TransformEmitter::getHandle(const std::string& lumName) {
    auto it = handles_.find(lumName);
    if (it == handles_.end()) return "";
    return it->second.ssaName;
}

void TransformEmitter::consumeHandle(const std::string& lumName,
                                      const std::string& consumer) {
    auto it = handles_.find(lumName);
    if (it != handles_.end()) {
        it->second.consumed = true;
        it->second.consumedBy = consumer;
    }
}

void TransformEmitter::rebindHandle(const std::string& lumName,
                                     const std::string& newSSA) {
    auto it = handles_.find(lumName);
    if (it != handles_.end()) {
        it->second.ssaName = newSSA;
        it->second.consumed = false;
        it->second.consumedBy = "";
    }
}

// Output helpers

void TransformEmitter::indent() {
    for (int i = 0; i < indentLevel_; ++i) {
        output_ << "  ";
    }
}

void TransformEmitter::line(const std::string& s) {
    output_ << s << "\n";
}

void TransformEmitter::emit(const std::string& s) {
    output_ << s;
}

} // namespace lum
